concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}} - ${{github.ref}}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: jpetrucciani/black-check@24.2.0
      with:
        black_flags: -S
name: black-linter
on:
  repository_dispatch:
    types: trigger-ga___black-lint.yml
