concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}} - ${{github.ref}}
jobs:
  build:
    if: "github.repository == 'doocs/leetcode' &&\n(github.event_name != 'pull_request'\
      \ ||\n github.event.pull_request.head.repo.full_name == github.repository)\n"
    name: calibreapp/image-actions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Branch
      uses: actions/checkout@v4
    - continue-on-error: true
      id: calibre
      name: Compress Images
      uses: calibreapp/image-actions@main
      with:
        compressOnly: ${{ github.event_name != 'pull_request' }}
        githubToken: ${{ secrets.DOOCS_BOT_ACTION_TOKEN }}
    - continue-on-error: true
      if: 'github.event_name != ''pull_request'' &&

        steps.calibre.outputs.markdown != ''''

        '
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        body: ${{ steps.calibre.outputs.markdown }}
        branch-suffix: timestamp
        commit-message: 'chore: auto compress images'
        title: 'chore: auto compress images'
name: compress-images
on:
  repository_dispatch:
    types: trigger-ga___compress.yml
