concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}} - ${{github.ref}}
env:
  MKDOCS_API_KEYS: ${{ secrets.MKDOCS_API_KEYS }}
jobs:
  deploy:
    if: github.repository == 'doocs/leetcode'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: mkdocs
        ref: docs
    - continue-on-error: true
      run: 'mv -f mkdocs/* .

        mv solution/CONTEST_README.md docs/contest.md

        mv solution/CONTEST_README_EN.md docs-en/contest.md

        '
    - continue-on-error: true
      name: Configure Git Credentials
      run: 'git config user.name github-actions[bot]

        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

        '
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: 'mkdocs-material-

          '
    - continue-on-error: true
      name: Install dependencies
      run: 'python3 -m pip install --upgrade pip

        python3 -m pip install -r requirements.txt

        python3 -m pip install "mkdocs-material[imaging]"

        sudo apt-get install pngquant

        '
    - continue-on-error: true
      run: 'python3 main.py

        mkdocs build -f mkdocs.yml

        mkdocs build -f mkdocs-en.yml

        '
    - continue-on-error: true
      name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
name: deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
permissions:
  contents: write
