concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}} - ${{github.ref}}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        PR_OPENER: ${{ github.actor }}
      id: check_team
      name: Check Team Membership
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.DOOCS_BOT_ACTION_TOKEN }}
        script: "const PR_OPENER = process.env.PR_OPENER;\nconst comment = \n`\U0001F92D\
          \ \u611F\u8C22\u4F60\u7684\u63D0\u4EA4\uFF0C\u8BF7\u68C0\u67E5\u4F60\u7684\
          \u6539\u52A8\u662F\u5426\u7B26\u5408\u4EE5\u4E0B\u9879\u76EE\u89C4\u8303\
          \u3002\n\n### 1. \u683C\u5F0F\u5316\n\n\u6211\u4EEC\u9879\u76EE\u4E2D\u5404\
          \u79CD\u7F16\u7A0B\u8BED\u8A00\u4EE3\u7801\uFF08\u5305\u62EC\u6587\u6863\
          \uFF09\u6240\u91C7\u7528\u7684\u683C\u5F0F\u5316\u5DE5\u5177\u4E0D\u540C\
          \uFF0C\u63D0\u4EA4 pr \u4E4B\u524D\u5FC5\u987B\u786E\u4FDD\u4EE3\u7801\u3001\
          \u6587\u6863\u6B63\u786E\u683C\u5F0F\u5316\u3002\n\n-   .{md,js,ts,php,sql,rs}\
          \ \u91C7\u7528 prettier\n-   .{c,cpp,java} \u91C7\u7528 clang-format\n-\
          \   .{py} \u91C7\u7528 black\n-   .{go} \u91C7\u7528 gofmt\n-   \u5176\u5B83\
          \u5F85\u5B8C\u5584\n\n### 2. Git \u63D0\u4EA4\u4FE1\u606F\n\n\u6211\u4EEC\
          \u9879\u76EE\u9075\u5FAA [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#)\
          \ \u89C4\u8303\uFF0C\u6211\u4EEC\u5E0C\u671B\u4F60\u7684\u63D0\u4EA4\u4FE1\
          \u606F\u5C3D\u53EF\u80FD\u4E0E\u9879\u76EE\u4FDD\u6301\u4E00\u81F4\u3002\
          \n\n-   \u65B0\u589E\u6216\u4FEE\u6539\u9898\u89E3\uFF1Afeat: add/update\
          \ solution(s) to lc problem(s): No.xxxx\n-   \u4FEE\u590D\u9519\u8BEF\uFF1A\
          fix: xxxx\n-   \u65E5\u5E38\u7EF4\u62A4\uFF1Achore: xxx\n\n### 3. \u5176\
          \u5B83\u8865\u5145\n\n\u65B0\u589E\u9898\u89E3\u53CA\u4EE3\u7801\u65F6\uFF0C\
          \u9700\u8981\u521B\u5EFA Solution.xxx \u6E90\u4EE3\u7801\u6587\u4EF6\uFF08\
          \u5982\u679C\u5DF2\u5B58\u5728\uFF0C\u8BF7\u786E\u8BA4\u7B97\u6CD5\u662F\
          \u5426\u66F4\u4F18\uFF0C\u662F\u5219\u8986\u76D6\u5DF2\u6709\u7B97\u6CD5\
          \u4EE3\u7801\uFF09\uFF0C\u540C\u65F6\uFF0C\u9700\u8981\u5728 README.md \u4EE5\
          \u53CA README_EN.md \u4E2D\u6DFB\u52A0\u5BF9\u5E94\u7684\u4EE3\u7801\u7247\
          \u6BB5\uFF08\u82F1\u6587\u6587\u4EF6\u4E2D\u4E0D\u8981\u51FA\u73B0\u4E2D\
          \u6587\u6CE8\u91CA\uFF09\n\u53E6\u5916\uFF0C\u7F16\u7801\u98CE\u683C\uFF08\
          \u6BD4\u5982\u53D8\u91CF\u3001\u51FD\u6570\u7684\u547D\u540D\uFF09\uFF0C\
          \u5C3D\u91CF\u8DDF\u9879\u76EE\u5DF2\u6709\u4EE3\u7801\u4FDD\u6301\u4E00\
          \u81F4\u3002 \n\n---\n\n\U0001F92D Thank you for your contribution. Please\
          \ check if your changes comply with the following project specifications.\
          \ \n\n### 1. Formatting\n\nWe use different formatting tools for various\
          \ programming languages (including documentation) in our project. You must\
          \ ensure that the code and documentation are correctly formatted before\
          \ submitting a pr.\n\n-   .{md,js,ts,php,sql,rs} use prettier\n-   .{c,cpp,java}\
          \ use clang-format\n-   .{py} use black\n-   .{go} use gofmt\n-   Others\
          \ to be improved\n\n### 2. Git Commit Message\n\nOur project follows the\
          \ [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#).\
          \ We hope that your submission information is as consistent as possible\
          \ with the project.\n\n-   Add or modify solutions: feat: add/update solution(s)\
          \ to lc problem(s): No.xxxx\n-   Fix errors: fix: xxxx\n-   Routine maintenance:\
          \ chore: xxx\n\n### 3. Other notes\n\nWhen adding solutions and code, you\
          \ need to create a Solution.xxx source code file (if it already exists,\
          \ please confirm whether the algorithm is better, if yes, overwrite the\
          \ existing algorithm code), and at the same time, you need to add the corresponding\
          \ code snippets in README.md and README_EN.md (do not have Chinese comments\
          \ in the English file)\nIn addition, the coding style (such as the naming\
          \ of variables and functions) should be as consistent as possible with the\
          \ existing code in the project. \n<!-- Sticky Pull Request Comment -->`\n\
          \nconst checkTeamMembership = async () => {\n  try {\n      const response\
          \ = await github.request('GET /orgs/{org}/teams/{team_slug}/members', {\n\
          \      org: 'doocs',\n      team_slug: 'leetcode-algorithm',\n        headers:\
          \ {\n          'X-GitHub-Api-Version': '2022-11-28'\n        }\n      })\n\
          \    const teamMemberships = response.data;\n    const isTeamMember = teamMemberships.some(member\
          \ => member.login === PR_OPENER);\n    if (isTeamMember) {\n        console.log(`The\
          \ user ${PR_OPENER} is a member of the team. Terminating with the workflow.`);\n\
          \        return\n    } else {\n      console.log(`The user ${PR_OPENER}\
          \ is not a member of the team. Proceeding the workflow.`);\n      github.rest.issues.createComment({\n\
          \        issue_number: context.issue.number,\n        owner: context.repo.owner,\n\
          \        repo: context.repo.repo,\n        body: comment\n      })\n   \
          \ }\n  } catch (error) {\n    console.log(PR_OPENER)\n    console.log(error)\n\
          \  }\n  }\n  checkTeamMembership();"
name: pr-checker
on:
  repository_dispatch:
    types: trigger-ga___pr-checker.yml
